--  Erzeugt von tools/build_matrix.py. Nicht von Hand aendern.
--  Alles, was ein Ausloeser abspielen kann: Barks und gebaute Questzeilen.
--  n = Eintrag, s = Situation, d = Dauer, st = Stufe, w = Gewicht, a = b|q
return {
  { n = "cl_1897d495012b6000", s = "abschied", d = 1.5, a = "q", t = "Bis dann, V." },
  { n = "cl_18982e23922b6000", s = "abschied", d = 1.5, a = "q", t = "Bis dahaaaann!" },
  { n = "cl_14ab207df129f000", s = "alltag", d = 7.1, a = "q", t = "Was auch immer du jetzt vorhast ... Kann ich irgendwie helfen?" },
  { n = "cl_1a0fbd86992b6000", s = "alltag", d = 6.8, a = "q", t = "Ich hab was richtig Großes. Sag’s dir heute Abend. Ach so – was willst du auf " },
  { n = "cl_1a0fe8a4772b6000", s = "alltag", d = 6.5, a = "q", t = "Igitt. Das sind zwei Wörter, die nicht in denselben Satz gehören. Schon gar ni" },
  { n = "cl_1a0fe9bfde2b6000", s = "alltag", d = 5.6, a = "q", t = "Was?! Und als Nächstes sagst du mir, du atmest nicht gern? Wie kann man keine " },
  { n = "cl_1786566a832fc000", s = "alltag", d = 3.9, a = "q", t = "Hast du ’ne Kippe?" },
  { n = "cl_396871fa77a71000", s = "alltag", d = 3.8, a = "q", t = "Wie trinkst du deinen? Heh, genau wie ich." },
  { n = "cl_1a6cd20de02fc004", s = "alltag", d = 3.1, a = "q", t = "Schon gelangweilt? Wir können weiter, wenn du willst." },
  { n = "cl_1a6c24d46f2fc000", s = "alltag", d = 2.8, a = "q", t = "Mal sehen, was wir noch so alles finden." },
  { n = "cl_1a6cd20dde2fc000", s = "alltag", d = 2.7, a = "q", t = "Willst du schon weg? Kein Sightseeing?" },
  { n = "cl_1a716d4e8a2b6000", s = "alltag", d = 2.4, a = "q", t = "Sieh dich um ..." },
  { n = "cl_3968769546a71000", s = "alltag", d = 2.3, a = "q", t = "Ooooh, ausgefallen." },
  { n = "cl_1afc15dc392fc004", s = "alltag", d = 2.2, a = "q", t = "Was ist sonst so in deinem Leben los?" },
  { n = "cl_3968743729a71000", s = "alltag", d = 2.1, a = "q", t = "Ich brüh was auf." },
  { n = "bump_var_2", s = "alltag", d = 2.0, a = "b", t = "Komm schon, ernsthaft?" },
  { n = "cl_15a8a4c8875ae000", s = "alltag", d = 1.8, a = "q", t = "Und? Was sagst du?" },
  { n = "bump_var_1", s = "alltag", d = 1.7, a = "b", t = "Hey, pass auf ..." },
  { n = "cl_396b7ccf489ce000", s = "alltag", d = 1.7, a = "q", t = "Wie geht’s so?" },
  { n = "cl_18552511902fc000", s = "alltag", d = 1.5, a = "q", t = "Wie sieht’s aus?" },
  { n = "cl_15a89ee0355ae010", s = "alltag", d = 1.4, a = "q", t = "Machen wir weiter." },
  { n = "cl_1806ce4c842fc000", s = "alltag", d = 1.4, a = "q", t = "Was machen wir?" },
  { n = "cl_1afc0918ac2fc000", s = "alltag", d = 1.2, a = "q", t = "Was gibt’s Neues?" },
  { n = "cl_189d4f49e02b6000", s = "arbeit", d = 3.5, a = "q", t = "Du, meine Liebe, wirst mit mir eine Virtu machen. / Du, Kumpel, wirst mit mir " },
  { n = "cl_1bde5efe6529f000", s = "blick", d = 1.1, st = 1, a = "q", t = "Was denn?" },
  { n = "cl_39669645a8a4e000", s = "blick", d = 1.0, st = 1, a = "q", t = "Alles in Ordnung, V?" },
  { n = "cl_3966964c69a4e000", s = "blick", d = 0.8, st = 1, a = "q", t = "Alles in Ordnung bei dir?" },
  { n = "cl_18ff52f8fd2b6000", s = "blick", d = 4.3, st = 2, a = "q", t = "Schon besser. Dachte für ’n Moment, du bist ’ne Langweilerin. / Schon besser. " },
  { n = "cl_1a676ce3032fc000", s = "blick", d = 4.2, st = 2, a = "q", t = "Außen tough ... und innen süß." },
  { n = "cl_3966891225a4e000", s = "blick", d = 3.2, st = 2, a = "q", t = "Hmmm … Außen tough und innen süß." },
  { n = "cl_1a9f0c7fe02fc000", s = "einladung", d = 4.5, a = "q", t = "Cool. Heute Abend in der Hütte am See. Lass mich nicht warten." },
  { n = "cl_1a9f085b672fc000", s = "einladung", d = 4.1, a = "q", t = "Klar. Heute Abend in der Hütte am See. Wir sehen uns dort?" },
  { n = "cl_39675ce5d69ce000", s = "einladung", d = 1.4, a = "q", t = "Lass mich nicht warten." },
  { n = "cl_18fa35b1a12b6000", s = "fahrzeug", d = 6.3, a = "q", t = "Fahr hin, wenn du willst. Ich denke, ich bleib noch ein bisschen hier." },
  { n = "cl_1a4e3b3a374ea000", s = "fahrzeug", d = 2.4, a = "q", t = "Ich warte im Auto. Beeil dich, okay?" },
  { n = "cl_1bde5d7e5429f000", s = "fahrzeug", d = 2.1, a = "q", t = "Mhm. Ich komm mit." },
  { n = "cl_16bf05739e2b6000", s = "fahrzeug", d = 2.0, a = "q", t = "Ja. Fahren wir zusammen?" },
  { n = "cl_1bde5dd1d429f000", s = "fahrzeug", d = 1.3, a = "q", t = "Ich komm mit." },
  { n = "cl_157e1b71452fc000", s = "fahrzeug", d = 1.1, a = "q", t = "Steig ein." },
  { n = "cl_18a6e78c9e2b6000", s = "flirt", d = 5.5, a = "q", t = "Und das andere ... Na ja, ich tauch nicht mit jeder. / Und das andere ... Na j" },
  { n = "cl_1897f7fb1a2b6000", s = "flirt", d = 5.2, a = "q", t = "Jetzt mach keinen Rückzieher mehr. Benutz einfach deine Fantasie." },
  { n = "cl_1a67403cc92fc004", s = "flirt", d = 5.0, a = "q", t = "Ich hab gerade was Komisches gehört ... Klang wie Nörgelei ...?" },
  { n = "cl_18983199cf2b6000", s = "flirt", d = 3.8, a = "q", t = "Na ja, glaub, ich hab genau das Richtige, um dich abzulenken." },
  { n = "cl_1a9f63e7252b6000", s = "flirt", d = 2.8, a = "q", t = "Du hast meine Pläne ruiniert, weißt du?" },
  { n = "cl_189736fe942b6000", s = "flirt", d = 2.7, a = "q", t = "Interessante Leute langweilen sich eben selten." },
  { n = "cl_189806a8512b6000", s = "flirt", d = 2.7, a = "q", t = "Aber vertrau mir, es wird sich lohnen." },
  { n = "cl_19eba4297c2b6000", s = "flirt", d = 2.7, a = "q", t = "Ich summe ein Lied, du sagst mir, welches es ist." },
  { n = "cl_1812474b462b6000", s = "flirt", d = 2.5, a = "q", t = "Da haben sich zwei gefunden." },
  { n = "cl_1897f8b7412b6000", s = "flirt", d = 2.5, a = "q", t = "Sag nicht, ich hätte dich nicht gewarnt." },
  { n = "cl_39675dc8759ce000", s = "flirt", d = 2.1, a = "q", t = "Du hast echt Talent, Kleines." },
  { n = "cl_18830b966a2b6000", s = "flirt", d = 4.7, st = 2, a = "q", t = "Oh, heißt das, mein Timing war perfekt, oder denkst du immer an mich?" },
  { n = "cl_189c5847c42b6000", s = "flirt", d = 3.9, st = 2, a = "q", t = "Wenn man das bedenkt, siehst du sogar sensationell aus. / Ach, komm schon, red" },
  { n = "cl_1afc12f00d2fc000", s = "initiative", d = 7.6, a = "q", t = "Oh, eh ich’s vergesse: Da hat so ’ne Elizabeth angerufen. Hat wohl einen Job f" },
  { n = "cl_1afc08ecff2fc000", s = "initiative", d = 5.7, a = "q", t = "Hab grad an dich gedacht. Und ehe du fragst ... In meinen Gedanken warst du na" },
  { n = "cl_1a67b32f202b6000", s = "initiative", d = 5.3, a = "q", t = "Aber deswegen ruf ich nicht an. Ich will dich um einen Gefallen bitten." },
  { n = "cl_18795a9ae52fc000", s = "initiative", d = 4.9, a = "q", t = "Wenn du das willst ... Oder komm einfach vorbei, wenn du magst." },
  { n = "cl_1b07df75762b6000", s = "initiative", d = 3.7, a = "q", t = "Gern. Passt mir gut, ich sitz grad eh am Steuer." },
  { n = "cl_1b0b9169282b6000", s = "initiative", d = 3.2, a = "q", t = "Ich bin für dich da, V. Ruf jederzeit an." },
  { n = "cl_1974ca6f6d2b6000", s = "initiative", d = 2.4, a = "q", t = "Wollte dich um ’nen Gefallen bitten." },
  { n = "cl_1b07e0e36d2b6000", s = "initiative", d = 2.3, a = "q", t = "Für dich hab ich den ganzen Tag." },
  { n = "cl_1b0791cfae2b6000", s = "initiative", d = 1.9, a = "q", t = "Wir haben alle Zeit der Welt." },
  { n = "cl_181ba067292fc000", s = "initiative", d = 1.3, a = "q", t = "Kommst du vorbei?" },
  { n = "cl_1a6d33c7952fc000", s = "kampf", d = 3.4, a = "q", t = "Kommeee! Die sind so gut wie erledigt!" },
  { n = "battlecry_curse_var_3", s = "kampf", d = 2.9, a = "b", t = "Hey, V! Mach was, verdammte Scheiße!" },
  { n = "cl_181c6d75ad2fc000", s = "kampf", d = 2.9, a = "q", t = "Pass auf – da könnten Leute sein." },
  { n = "elite_warning_var_1", s = "kampf", d = 2.7, a = "b", t = "Wo haben die nur diese Ausrüstung her?" },
  { n = "battlecry_morale_var_1", s = "kampf", d = 2.5, a = "b", t = "Jetzt bin ich richtig sauer!" },
  { n = "cl_174f5826962b6000", s = "kampf", d = 2.5, a = "q", t = "Vorsicht. Da sind zwei." },
  { n = "elite_warning_var_2", s = "kampf", d = 2.3, a = "b", t = "Ordentlich ausgestattet, die Typen!" },
  { n = "grenade_throw", s = "kampf", d = 2.3, a = "b", t = "Na, wie schmeckt dir das?!" },
  { n = "grenade_enemy_var_3", s = "kampf", d = 2.2, a = "b", t = "In Deckung! Granate!" },
  { n = "cl_16be4522142fc000", s = "kampf", d = 2.1, a = "q", t = "Ich lenk sie ab, du erledigst sie." },
  { n = "battlecry_morale_var_3", s = "kampf", d = 2.1, a = "b", t = "Jetzt mach ich ernst!" },
  { n = "reloading_var_3", s = "kampf", d = 2.1, a = "b", t = "Warte kurz, muss nachladen." },
  { n = "enemy_warning_var_2", s = "kampf", d = 2.1, a = "b", t = "Sie sind hier. Bleib wachsam." },
  { n = "reloading_var_2", s = "kampf", d = 2.0, a = "b", t = "Deck mich, ich lade nach!" },
  { n = "grenade_enemy_var_2", s = "kampf", d = 1.9, a = "b", t = "Achtung, Granate!" },
  { n = "danger_var_1", s = "kampf", d = 1.9, a = "b", t = "Oh, Scheiße!" },
  { n = "cl_16bdd8ff5d2fc000", s = "kampf", d = 1.8, a = "q", t = "Jetzt! Mach sie fertig!" },
  { n = "battlecry_morale", s = "kampf", d = 1.8, a = "b", t = "Hast es so gewollt!" },
  { n = "battlecry_morale_var_2", s = "kampf", d = 1.8, a = "b", t = "Hast es so gewollt!" },
  { n = "reloading_var_1", s = "kampf", d = 1.7, a = "b", t = "Ich muss nachladen." },
  { n = "battlecry_curse_var_2", s = "kampf", d = 1.6, a = "b", t = "Was zur Hölle?" },
  { n = "cl_18b6bc8f672fc000", s = "kampf", d = 1.6, a = "q", t = "Kannst du sie ausschalten?" },
  { n = "cl_180700ef0d2fc000", s = "kampf", d = 1.5, a = "q", t = "Erledige die, schnell." },
  { n = "grenade_enemy_var_1", s = "kampf", d = 1.4, a = "b", t = "Granate!" },
  { n = "combat_aggro_bark_var_1", s = "kampf", d = 1.4, w = 0.20, a = "b", t = "Echt jetzt?!" },
  { n = "enemy_warning_var_1", s = "kampf", d = 1.4, a = "b", t = "Da kommen sie!" },
  { n = "danger_var_3", s = "kampf", d = 1.4, a = "b", t = "Bin bei dir." },
  { n = "combat_aggro_bark_var_2", s = "kampf", d = 1.3, w = 0.50, a = "b", t = "Aaah!" },
  { n = "danger", s = "kampf", d = 1.2, a = "b", t = "Achtung!" },
  { n = "danger_var_2", s = "kampf", d = 1.2, a = "b", t = "Achtung!" },
  { n = "battlecry_curse", s = "kampf", d = 1.2, a = "b", t = "Fuuuck!" },
  { n = "battlecry_curse_var_1", s = "kampf", d = 1.2, a = "b", t = "Fuuuck!" },
  { n = "cl_396690f54aa4e000", s = "kampf_ende", d = 4.4, a = "q", t = "Okay, jetzt geht der Spaß erst richtig los." },
  { n = "cl_18070264fd2fc000", s = "kampf_ende", d = 4.1, a = "q", t = "Fresst das, Arschlöcher. Scheint, als hättest du alle erwischt." },
  { n = "combat_ended_var_1", s = "kampf_ende", d = 2.8, a = "b", t = "Oh, das war’s. Wir haben’s geschafft." },
  { n = "combat_ended_var_2", s = "kampf_ende", d = 2.8, a = "b", t = "Sieh uns an. Nicht totzukriegen." },
  { n = "cl_1a76a081672b6000", s = "kampf_ende", d = 2.2, a = "q", t = "Dein Ernst? Die ist großartig!" },
  { n = "cl_39675beeb89ce000", s = "kampf_ende", d = 1.9, a = "q", t = "Heeey, nicht schlecht." },
  { n = "cl_1a9600232a2fc000", s = "kampf_ende", d = 1.7, a = "q", t = "Hey, nicht schlecht." },
  { n = "cl_18fa36f3f82b6000", s = "naehe", d = 7.0, a = "q", t = "Ich mag dich. Ich will dich oft sehen. Aus meiner Sicht gibt’s da nichts zu üb" },
  { n = "cl_18fe75e7ff3bc000", s = "naehe", d = 6.8, a = "q", t = "Und solltest du je Hilfe brauchen, du weißt, dass ich für dich da bin, ja? Imm" },
  { n = "cl_1878a052fd2fc000", s = "naehe", d = 5.5, a = "q", t = "Ist es dein, ähm, blinder Passagier? Wird es schlimmer?" },
  { n = "cl_197a02720e2b6000", s = "naehe", d = 5.4, a = "q", t = "Ich ... will einfach nicht über irgendwas davon nachdenken. Nicht heute." },
  { n = "cl_1401fd943a2fc000", s = "naehe", d = 4.0, a = "q", t = "Scheiße ... Ich hab Angst, V." },
  { n = "cl_19dbc1edd129f000", s = "naehe", d = 3.1, a = "q", t = "Hab davon geträumt, wie es wird, wenn wir’s endlich schaffen ..." },
  { n = "cl_175e1a1cba386000", s = "naehe", d = 2.9, a = "q", t = "Ich weiß nicht, was ich mache, wenn du nicht mehr da bist." },
  { n = "cl_18f9fc80d42b6000", s = "naehe", d = 2.1, a = "q", t = "Ich dich auch, V ..." },
  { n = "cl_184f1ffc6b2fc000", s = "naehe", d = 2.0, a = "q", t = "Hey, setzt du dich ein bisschen zu mir?" },
  { n = "cl_170a369e224e6000", s = "naehe", d = 1.9, a = "q", t = "Ich bin froh, dass wir das tun." },
  { n = "cl_184f3f3bbe2fc000", s = "naehe", d = 1.6, a = "q", t = "Gib mir deine Hand, V." },
  { n = "cl_185efbe0f1502010", s = "reibung", d = 3.9, a = "q", t = "Sei vorsichtig, okay? Ich warte hier auf dich." },
  { n = "cl_18f9e3bc672b6000", s = "reibung", d = 3.8, a = "q", t = "Puh, manchmal hast du echt ein Brett vorm Kopf." },
  { n = "cl_39669585fca4e000", s = "reibung", d = 3.3, a = "q", t = "Jepp, bin sofort da. Warte auf mich." },
  { n = "cl_16b50051b62fc000", s = "reibung", d = 2.9, a = "q", t = "Jepp. Bin sofort da. Warte auf mich." },
  { n = "cl_16b5046d372fc000", s = "reibung", d = 2.9, a = "q", t = "V, warte. Ich bin ganz nah." },
  { n = "cl_1f46422d992b6008", s = "reibung", d = 2.9, a = "q", t = "Komm schon! Keine falsche Scheu." },
  { n = "cl_1a7bd32bec2fc000", s = "reibung", d = 2.8, a = "q", t = "V, lass uns abhauen." },
  { n = "cl_1787cc94372cd000", s = "reibung", d = 2.7, a = "q", t = "Okay, ich warte hier auf dich." },
  { n = "cl_157e1b71602fc008", s = "reibung", d = 2.7, a = "q", t = "Okay ... Aber lass dir nicht zu viel Zeit." },
  { n = "follow_me_1", s = "reibung", d = 2.7, a = "b", t = "Was ist los? Hör auf zu trödeln." },
  { n = "phone_urge_var_2", s = "reibung", d = 2.7, a = "b", t = "Bist du da? Kannst du mich hören?" },
  { n = "cl_1a6c40ed992fc000", s = "reibung", d = 2.6, a = "q", t = "Sag Bescheid, wenn du weiter willst." },
  { n = "interrupt_var_1", s = "reibung", d = 2.5, a = "b", t = "Okay, wir setzen das später fort." },
  { n = "cl_19ec472e462b6000", s = "reibung", d = 2.5, a = "q", t = "Das gefällt dir gar nicht, hm?" },
  { n = "hurry_up_var_2", s = "reibung", d = 2.5, a = "b", t = "Wir haben was vor, schon vergessen?" },
  { n = "cl_1a6d3771f92fc000", s = "reibung", d = 2.5, a = "q", t = "Aye aye, Käpt’n – mir nach." },
  { n = "cl_1a6d277cc12fc000", s = "reibung", d = 2.4, a = "q", t = "Na dann komm. Ich will dir was zeigen." },
  { n = "cl_185fea344a2b6000", s = "reibung", d = 2.3, a = "q", t = "Deine Entscheidung, aber trödel nicht." },
  { n = "follow_me", s = "reibung", d = 2.3, a = "b", t = "Komm schon, V, bleib bei mir." },
  { n = "follow_me_2", s = "reibung", d = 2.3, a = "b", t = "Komm schon, V, bleib bei mir." },
  { n = "cl_137c5715552b1000", s = "reibung", d = 2.2, a = "q", t = "Warum, gefällt’s dir nicht?" },
  { n = "hurry_up_var_3", s = "reibung", d = 2.1, a = "b", t = "Konzentration, V." },
  { n = "cl_14edc33d565b2000", s = "reibung", d = 2.1, a = "q", t = "V? Worauf wartest du?" },
  { n = "cl_1a6c5010692fc004", s = "reibung", d = 2.0, a = "q", t = "Was sagst du, wollen wir weiter?" },
  { n = "hurry_up_var_1", s = "reibung", d = 1.9, a = "b", t = "Na? Los jetzt!" },
  { n = "cl_17c00d5613610000", s = "reibung", d = 1.9, a = "q", t = "Na los, worauf wartest du?" },
  { n = "interrupt", s = "reibung", d = 1.9, a = "b", t = "Hab ich dich gelangweilt?" },
  { n = "interrupt_var_2", s = "reibung", d = 1.9, a = "b", t = "Hab ich dich gelangweilt?" },
  { n = "urge_var_1", s = "reibung", d = 1.8, a = "b", t = "Was ist mit dir los?" },
  { n = "phone_urge_var_1", s = "reibung", d = 1.8, a = "b", t = "Äh ... V?" },
  { n = "cl_183b56df2f2b600c", s = "reibung", d = 1.7, a = "q", t = "So lang hat das nicht Zeit." },
  { n = "cl_1a76bc30fd2fc004", s = "reibung", d = 1.7, a = "q", t = "Komm, gehen wir." },
  { n = "urge", s = "reibung", d = 1.6, a = "b", t = "Komm schon, V." },
  { n = "urge_var_2", s = "reibung", d = 1.6, a = "b", t = "Komm schon, V." },
  { n = "cl_16bf45cbac2fc000", s = "reibung", d = 1.6, a = "q", t = "Wart ’ne Sekunde auf mich." },
  { n = "cl_1a7b10f6e62fc000", s = "reibung", d = 1.5, a = "q", t = "V, warte noch." },
  { n = "cl_1aa440794d2fc000", s = "reibung", d = 1.4, a = "q", t = "Schon unterwegs." },
  { n = "cl_39675fea699ce000", s = "reibung", d = 1.3, a = "q", t = "Komm schon, V. Bleib bei mir." },
  { n = "cl_14aaba91a329f000", s = "sorge", d = 9.9, a = "q", t = "Du kommst mir ... anders vor. Bist irgendwie ... abwesend. Denkst du an Mikosh" },
  { n = "cl_1a82306830610000", s = "sorge", d = 6.6, a = "q", t = "Ich ... muss das verarbeiten, und zwar allein." },
  { n = "cl_1a33ca85c72b6000", s = "sorge", d = 5.5, a = "q", t = "Wenn ich irgendwie helfen kann ... egal, wie ... musst du’s nur sagen." },
  { n = "cl_14aabd878129f000", s = "sorge", d = 5.2, a = "q", t = "Du bist schon seit ’ner Woche so, V. Ich hab das Gefühl ... du verschweigst mi" },
  { n = "cl_1892e2683e2b6000", s = "sorge", d = 4.8, a = "q", t = "Oh, ich kenne diese Stimme, V. Alles ... okay?" },
  { n = "cl_1ef8b0c1f442f000", s = "sorge", d = 4.5, a = "q", t = "Schön langsam atmen. Ruhig. Alles okay, dir geht’s gut." },
  { n = "cl_175e197aaa386000", s = "sorge", d = 4.3, a = "q", t = "Scheiße, V. Ich dachte, du bist tot." },
  { n = "cl_14ab1431b629f000", s = "sorge", d = 4.3, a = "q", t = "Pass auf dich auf, V. Komm in einem Stück zurück." },
  { n = "cl_1afd6f18ec2fc000", s = "sorge", d = 4.1, a = "q", t = "Kann ich verstehen, V. Ehrlich gesagt würde das auch ’ne Weile dauern." },
  { n = "grapple", s = "sorge", d = 3.9, a = "b", t = "Ungh ... Aaargh ... Lass ... los!" },
  { n = "cl_18a2feb32f2fc004", s = "sorge", d = 3.5, a = "q", t = "Was zum Teufel, V? Bist du ... krank?" },
  { n = "player_fallback_var_2", s = "sorge", d = 3.5, a = "b", t = "V, pass besser auf! Tot nützt du niemandem!" },
  { n = "player_fallback_var_1", s = "sorge", d = 2.8, a = "b", t = "Pass auf, verdammt! Schalt dein Hirn ein." },
  { n = "cl_1b971f17262b6000", s = "sorge", d = 2.8, a = "q", t = "Aber wenn du Zeit hast, sag mir Bescheid, okay?" },
  { n = "player_fallback_var_3", s = "sorge", d = 2.8, a = "b", t = "Alles okay? Schnauf mal kurz durch." },
  { n = "cl_185efbe0f5502008", s = "sorge", d = 2.7, a = "q", t = "Hey, es war ja nicht deine Schuld ..." },
  { n = "cl_1a33ace66d2b6000", s = "sorge", d = 2.5, a = "q", t = "V? Du siehst nicht gut aus ..." },
  { n = "cl_1f0c4ccf9242f000", s = "sorge", d = 2.3, a = "q", t = "Pass auf dich auf da draußen, V." },
  { n = "cl_1a7b4c53a32b6000", s = "sorge", d = 2.3, a = "q", t = "Hey, langsam ... Ganz ruhig." },
  { n = "cl_1bd4dab9c42b6000", s = "sorge", d = 2.2, a = "q", t = "Hab Schüsse gehört. Lebst du noch?" },
  { n = "cl_1a95b684a12b6000", s = "sorge", d = 2.2, a = "q", t = "Du solltest langsam machen." },
  { n = "cl_28aa62967b4ea000", s = "sorge", d = 2.1, a = "q", t = "Ganz ruhig, ist alles okay?" },
  { n = "cl_396692eeb0a4e000", s = "sorge", d = 2.0, a = "q", t = "Tief durchatmen." },
  { n = "cl_1f4640da642b6000", s = "sorge", d = 2.0, a = "q", t = "Denk nicht zu viel drüber nach, okay?" },
  { n = "cl_1f45f8b07b2b6008", s = "sorge", d = 1.9, a = "q", t = "Ganz ruhig, ist alles okay?" },
  { n = "cl_1ef8b0825f42f000", s = "sorge", d = 1.8, a = "q", t = "Sag schon, wie fühlst du dich?" },
  { n = "cl_19f164ba6d2b6004", s = "sorge", d = 1.7, a = "q", t = "Pass auf dich auf, V." },
  { n = "cl_1ef8b0186b42f000", s = "sorge", d = 1.6, a = "q", t = "Alles in Ordnung, V?" },
  { n = "cl_1f46421f852b6008", s = "sorge", d = 1.6, a = "q", t = "Alles in Ordnung bei dir?" },
  { n = "cl_1f45f63cf42b6000", s = "sorge", d = 1.4, a = "q", t = "Geht’s dir wirklich gut?" },
  { n = "body_warning_var_1", s = "stealth", d = 3.1, a = "b", t = "Lass uns hier klar Schiff machen, sonst fliegen wir auf." },
  { n = "detection_warning_var_1", s = "stealth", d = 2.9, a = "b", t = "Verschwinde da, sonst sehen sie uns!" },
  { n = "cl_1a95de1e182fc000", s = "stealth", d = 2.4, a = "q", t = "Danach schleichen wir uns vorbei ..." },
  { n = "detection_warning_var_2", s = "stealth", d = 2.4, a = "b", t = "Vorsicht, die haben was gehört!" },
  { n = "stealth_restored_var_1", s = "stealth", d = 2.2, a = "b", t = "Perfekt, die sehen uns nicht mehr." },
  { n = "body_warning_var_2", s = "stealth", d = 2.2, a = "b", t = "Versteck den Körper, okay?" },
  { n = "camera_warning_var_1", s = "stealth", d = 2.1, a = "b", t = "Pass auf die Kameras auf, okay?" },
  { n = "camera_warning_var_2", s = "stealth", d = 2.1, a = "b", t = "Die haben hier alles im Blick." },
  { n = "stealth_restored_var_2", s = "stealth", d = 1.8, a = "b", t = "Die haben wir abgeschüttelt." },
  { n = "cl_180ca4ff2f2fc000", s = "stealth", d = 1.6, a = "q", t = "Gesichert. Geh weiter." },
  { n = "stealth_warning_bark_var_2", s = "stealth", d = 1.3, a = "b", t = "Vorsicht!" },
  { n = "stealth_warning_bark_var_1", s = "stealth", d = 1.2, a = "b", t = "Sei still!" },
  { n = "cl_180ca5fe922fc000", s = "stealth", d = 1.2, a = "q", t = "Mist, entdeckt!" },
  { n = "cl_16bf45bffc2fc000", s = "stolz", d = 3.4, a = "q", t = "Du verschwendest keine Munition. Bin beeindruckt." },
  { n = "cl_39675eebd79ce000", s = "stolz", d = 1.7, a = "q", t = "Genial, oder?" },
  { n = "cl_199d9ab23f29f000", s = "umgebung", d = 11.1, a = "q", t = "Mhm. Von hier aus sieht die Stadt so weit weg und unschuldig aus. Komisches Ge" },
  { n = "cl_19562ed6af29f000", s = "umgebung", d = 6.9, a = "q", t = "Ich hab gerade erst erkannt, dass Night City nie richtig für mich war." },
  { n = "cl_19562ed6cf29f000", s = "umgebung", d = 6.0, a = "q", t = "Jedes Mal dachte ich, ich hätte ein Zuhause gefunden. Und jedes Mal wurde ich " },
  { n = "cl_1a7183520c2b6000", s = "umgebung", d = 4.3, a = "q", t = "Fast, als wären wir jenseits von Raum und Zeit. Wie in ’ner Schneekugel." },
  { n = "cl_136656bfaf2fc000", s = "umgebung", d = 2.5, a = "q", t = "Genießt du die Aussicht? / Hübsche Aussicht, Machoman?" },
  { n = "cl_1a6c40ec352fc004", s = "umgebung", d = 2.2, a = "q", t = "Wollen wir über den Platz schlendern?" },
  { n = "cl_1362d96a1b2fc000", s = "umgebung", d = 1.9, a = "q", t = "Beeindruckend, oder?" },
  { n = "cl_1a297fc3bf29f000", s = "umgebung", d = 1.8, a = "q", t = "Frag mich, ob’s mir fehlen wird ..." },
  { n = "cl_39687a048fa71000", s = "umgebung", d = 1.4, a = "q", t = "Genießt du die Aussicht?" },
  { n = "cl_1362da25582fc000", s = "umgebung", d = 1.2, st = 1, a = "q", t = "Gefällt’s dir?" },
  { n = "cl_135dba0e2a2fc000", s = "wasser", d = 4.3, a = "q", t = "Sehr gut, hat geklappt. Jetzt schwimm zu mir. / Sehr gut, das hat geklappt. Je" },
  { n = "cl_1a6cc1fb6c2fc000", s = "wasser", d = 4.1, a = "q", t = "Fühlt sich echt komisch an, hier durchzuschwimmen ..." },
  { n = "cl_15c177f5d44e2000", s = "wasser", d = 3.8, a = "q", t = "Schwimm nicht zu weit weg, ja? Sonst werden wir nur asynchron." },
  { n = "cl_1be51b21f02b6000", s = "wasser", d = 3.8, a = "q", t = "Tauch nicht allein ab. Der Anzug hält dem Druck nicht stand." },
  { n = "cl_1a6ce949fa2fc004", s = "wasser", d = 3.2, a = "q", t = "Komm, wir schwimmen noch ein bisschen weiter." },
  { n = "cl_1be5242cf12b6000", s = "wasser", d = 2.9, a = "q", t = "Komm nicht zu schnell hoch, das ist gefährlich." },
  { n = "cl_1be52435972b6000", s = "wasser", d = 2.0, a = "q", t = "Du steigst zu schnell hoch, V!" },
  { n = "cl_1b07ecef852b6000", s = "wiedersehen", d = 7.0, a = "q", t = "Ich lass es langsam angehen. Aber ich mach mich bald wieder an die Arbeit. Hab" },
  { n = "cl_1b07d5a1472b6000", s = "wiedersehen", d = 4.8, a = "q", t = "Mich auch. Ich wurde sogar schon gefragt, warum ich so strahle." },
  { n = "cl_1893611d242b6000", s = "wiedersehen", d = 4.2, a = "q", t = "Hoo, ich bin nur froh, dass du überhaupt an mich denkst." },
  { n = "cl_39668f23c9a4e000", s = "wiedersehen", d = 3.1, a = "q", t = "V! Siehst gut aus." },
  { n = "cl_2ffdc7962d571000", s = "wiedersehen", d = 3.1, a = "q", t = "Woher weißt du immer, wenn du mir fehlst?" },
  { n = "cl_39669188b9a4e000", s = "wiedersehen", d = 2.9, a = "q", t = "Ich bin froh, dass du da bist." },
  { n = "cl_1a7712a0b22fc000", s = "wiedersehen", d = 2.8, a = "q", t = "Hey V, danke dass du gekommen bist." },
  { n = "cl_1826c0c4492fc000", s = "wiedersehen", d = 2.6, a = "q", t = "V! Siehst gut aus! / V, du bist echt gekommen." },
  { n = "cl_0f339c53952e3010", s = "wiedersehen", d = 2.5, a = "q", t = "Hey, da bist du ja." },
  { n = "cl_1ee881e18b42f000", s = "wiedersehen", d = 2.2, a = "q", t = "V, da bist du ja!" },
  { n = "cl_18d9a13a264ea004", s = "wiedersehen", d = 2.1, a = "q", t = "Hey, V! Was geht?" },
  { n = "return_answer_var_1", s = "wiedersehen", d = 2.0, a = "b", t = "Worüber hatten wir geredet?" },
  { n = "cl_1b2f276faf2fc000", s = "wiedersehen", d = 1.9, a = "q", t = "Gut, dass du da bist." },
  { n = "cl_17c0a2ca2c610000", s = "wiedersehen", d = 1.8, a = "q", t = "Wird auch Zeit." },
  { n = "cl_16bf49d3352fc000", s = "wiedersehen", d = 1.5, a = "q", t = "Okay, ich bin da." },
  { n = "return_answer", s = "wiedersehen", d = 1.4, a = "b", t = "Du bist zurück." },
  { n = "return_answer_var_2", s = "wiedersehen", d = 1.4, a = "b", t = "Du bist zurück." },
  { n = "greeting_var_1", s = "wiedersehen", d = 1.4, a = "b", t = "Oh, hey!" },
  { n = "greeting", s = "wiedersehen", d = 1.1, a = "b", t = "Hey, V." },
  { n = "greeting_var_2", s = "wiedersehen", d = 1.1, a = "b", t = "Hey, V." },
  { n = "cl_18795a0a822fc000", s = "wohnung", d = 5.0, a = "q", t = "Das war’s schon. Glückwunsch, du hast jetzt Zugang zu meiner Wohnung." },
  { n = "cl_1a04f187642fc000", s = "wohnung", d = 4.8, a = "q", t = "Oh, du bist schon da? Hättest ja sagen können, dass du kein Fan von Türen bist" },
  { n = "cl_18feb70a322b600c", s = "wohnung", d = 4.3, a = "q", t = "Nein. Da. Unser Nest für heut Nacht. / Nein. Da drin. Ich übernachte da öfter " },
  { n = "cl_1a676388f12fc000", s = "wohnung", d = 3.5, a = "q", t = "Du musst furchtbar frieren. Ich brüh was auf." },
  { n = "cl_1a96129b222b6000", s = "wohnung", d = 2.5, a = "q", t = "Hier ist dein Kaffee. Endlich." },
  { n = "cl_18a2fa98762fc004", s = "wohnung", d = 2.4, a = "q", t = "Es ist spät. Du bist müde." },
  { n = "cl_18a2fa98762fc00c", s = "wohnung", d = 2.3, a = "q", t = "Wenn du willst, kannst du auf der Couch schlafen." },
  { n = "cl_19faf887702b6000", s = "zustimmung", d = 2.2, a = "q", t = "Da könntest du recht haben." },
  { n = "cl_1a674041712fc000", s = "zustimmung", d = 2.1, a = "q", t = "Wenn du meinst ..." },
  { n = "cl_1a7b507f262fc000", s = "zustimmung", d = 1.8, a = "q", t = "Sehe ich genauso." },
  { n = "cl_166b8c00b24ea000", s = "zustimmung", d = 1.7, a = "q", t = "Ich glaub, wir können." },
  { n = "cl_1a33d8c6a32b6000", s = "zustimmung", d = 1.6, a = "q", t = "Wie du willst." },
}
